# Generated by Django 3.1.2 on 2021-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
