# Generated by Django 3.1.2 on 2021-12-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20211201_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
